name: Update Trustpilot JSON (Debug Mode)

on:
  schedule:
    - cron: '0 */6 * * *'       # every 6h
  workflow_dispatch:             # manual trigger in Actions UI

permissions:
  contents: write                # Needed for git push

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch Trustpilot data
        env:
          API_KEY: ${{ secrets.TRUSTPILOT_API_KEY }}
          BU_ID: ${{ secrets.TRUSTPILOT_BUSINESS_UNIT_ID }}
        run: |
          # 1. Call Trustpilot
          response=$(curl -s -H "apikey: $API_KEY" \
            "https://api.trustpilot.com/v1/business-units/$BU_ID")
          
          # 2. Debug: Print raw API response
          echo "========== Trustpilot API Raw Response =========="
          echo "$response"
          echo "================================================="

          # 3. Try to extract trustScore and stars
          score=$(echo "$response" | jq '.statistics.trustScore')
          stars=$(echo "$response" | jq '.statistics.stars')

          echo "Extracted trustScore: $score"
          echo "Extracted stars: $stars"

          # 4. Build an ISO-8601 UTC timestamp
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          # 5. Write JSON with lastUpdated
          jq -n \
            --arg ts "$timestamp" \
            --argjson tr ${score:-0} \
            --argjson st ${stars:-0} \
            '{ trustScore: $tr, stars: $st, lastUpdated: $ts }' \
            > trustpilot.json

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if ! git diff --quiet; then
            git add trustpilot.json
            git commit -m "chore: update Trustpilot data"
            git push
          else
            echo "No changes to commit."
          fi
