name: Update Trustpilot JSON

on:
  schedule:
    # every 1 hours; adjust as you like
    - cron:  '0 */1 * * *'
  workflow_dispatch:   # allows manual runs

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch Trustpilot data
        env:
          API_KEY: ${{ secrets.TRUSTPILOT_API_KEY }}
          BU_ID:  ${{ secrets.TRUSTPILOT_BUSINESS_UNIT_ID }}
        run: |
          response=$(curl -s -H "apikey: $API_KEY" \
            "https://api.trustpilot.com/v1/business-units/$BU_ID")
          score=$(echo "$response" | jq '.statistics.trustScore')
          stars=$(echo "$response" | jq '.statistics.stars')
          printf '{"trustScore": %.1f, "stars": %.1f}' \
            "$score" "$stars" > trustpilot.json

      - name: Commit & Push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add trustpilot.json
          # only commit if changed
          git diff --quiet || git commit -m "chore: update Trustpilot data"
          git push
